# Generated by Django 4.2.21 on 2025-05-14 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
