# Generated by Django 4.2.21 on 2025-05-14 16:43

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime,timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.now() + timedelta(days=1)),
            preserve_default=False,
        ),
    ]
